server:
  port: 8181
  features: 
    observe:
      observers:
        health:
          details: true
    security:
      enabled: true

# Internal JWT configuration for service-to-service authentication
security:
  internal-jwt:
    secret: "${INTERNAL_JWT_SECRET:your-super-secure-secret-key-here-must-be-at-least-32-characters}"
    issuer: "payment-showcase"
    audience: "internal-apis"
    expiration-minutes: 15

# Logging Configuration
logging:
  level:
    root: INFO
    dev.lonecalvary78.app.payment.internal.bankaccount: DEBUG
    dev.lonecalvary78.app.bankaccount.security: DEBUG