apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: ghcr.io/lonecalvary78/payment-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8282
          env:
            - name: AWS_REGION
              value: ${TARGET_REGION}
            - name: DB_MODE
              value: "localstack"
            - name: DB_LOCALSTACK_ENDPOINT
              value: "http://localstack:4566"
            - name: DB_LOCALSTACK_REGION
              value: "us-east-1"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /observe/health/live
              port: 8282
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /observe/health/ready
              port: 8282
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
