# Microsoft Entra ID Configuration using MSAL
# Environment Variables (set in deployment)
# ENTRA_TENANT_ID=your-tenant-id
# ENTRA_CLIENT_ID=your-application-client-id  
# ENTRA_CLIENT_SECRET=your-client-secret
# INTERNAL_JWT_SECRET=your-super-secure-jwt-secret-key-here-must-be-at-least-32-characters

server:
  port: 8080
  features:
    security:
      enabled: true

# MSAL specific configuration
msal:
  tenant-id: "${ENTRA_TENANT_ID}"
  client-id: "${ENTRA_CLIENT_ID}"
  client-secret: "${ENTRA_CLIENT_SECRET}"
  
  # Authority URL
  authority: "https://login.microsoftonline.com/${ENTRA_TENANT_ID}"
  
  # Redirect URIs
  redirect-uri: "${REDIRECT_URI:http://localhost:8080/auth/callback}"
  
  # Scopes for the application
  scopes:
    - "https://graph.microsoft.com/User.Read"
    - "https://graph.microsoft.com/profile"
    - "https://graph.microsoft.com/email"
    - "api://payment-showcase/Payment.Process"
  
  # Cache configuration
  cache:
    enabled: true
    duration: "PT1H" # 1 hour
  
  # Token validation
  token-validation:
    validate-signature: true
    validate-issuer: true
    validate-audience: true
    leeway: "PT5M" # 5 minutes

# Microsoft Graph API configuration
graph:
  base-url: "https://graph.microsoft.com/v1.0"
  scopes:
    - "https://graph.microsoft.com/User.Read"
    - "https://graph.microsoft.com/Group.Read.All"

integration:
  bankaccount:
    endpoint: "http://localhost:8181"
  payment:
    endpoint: "http://localhost:8282"

# Security paths configuration
  
# Security paths configuration
security:
  # Internal JWT configuration for service-to-service authentication
  internal-jwt:
    secret: "${INTERNAL_JWT_SECRET:your-super-secure-secret-key-here-must-be-at-least-32-characters}"
    issuer: "payment-showcase"
    audience: "internal-apis"
    expiration-minutes: 15
  
  paths:
    # Public paths (no authentication required)
    public:
      - "/observe/health/**"
      - "/metrics"
      - "/auth/**"
    # Protected paths with roles
    protected:
      - path: "/payments/**"
        roles: ["PaymentUser", "PaymentAdmin"]
        methods: ["GET", "POST", "PUT", "DELETE"]
