name: payment-bff build and push
on:
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write      
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
              distribution: 'liberica'
              java-version: '21'
              cache: maven
          - name: copy project resources
            run: |
                cp -R ./payment-bff/src ./
                cp -R ./payment-bff/pom.xml ./
          - name: Run tests
            run: mvn test
    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
              distribution: 'liberica'
              java-version: '21'
              cache: maven
          - name: copy project resources
            run: |
                cp -R ./payment-bff/src ./
                cp -R ./payment-bff/pom.xml ./
          - name: Build with Maven
            run: mvn package -DskipTests
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./payment-bff/Dockerfile
              push: true
              build-args: |
                BUILD_VERSION=latest
                MAINTAINER_NAME=${{ github.repository_owner }}
              tags: |
                ghcr.io/${{ github.repository_owner }}/payment-bff:latest


