name: sonar-analysis
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - 'docs/**'
      - '.gitignore'
jobs:
  sonar-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: project-checkout
        uses: actions/checkout@v3
      - id: jdk-setup
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: maven
      - id: cache-sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - id: build-and-test
        run: |
            mvn clean test jacoco:report dependency:copy-dependencies -f bankaccount-api/pom.xml
            mvn clean test jacoco:report dependency:copy-dependencies -f payment-api/pom.xml
            mvn clean test jacoco:report dependency:copy-dependencies -f payment-bff/pom.xml
      - id: sonarqube-scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
